### ISSUE TITLE
Consolidate new-console-output test head.js files

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#16]
The current structure has the tests like this:
- actions
  - head.js
- components
  - head.js
- reducers
  - head.js

We could consolidate the head.js files into a single head file per test type. In order to do this, I believe we would need to register the files with the test harness like [shared-redux-head is](https://dxr.mozilla.org/mozilla-central/source/devtools/client/framework/moz.build#9).

```
TEST_HARNESS_FILES.xpcshell.devtools.client.framework.test += [
    'test/shared-redux-head.js',
]
```

This may require changing the directory name of new-console-output to not include dashes.

**Comment by bgrins** [comment]
Interesting problem with this - if I add a reference to a shared-head file at new-console-output/test in xpcshell.ini then run`./mach test devtools/client/webconsole/new-console-output/test/`it works, but if I `./mach test devtools/client/webconsole/new-console-output/test/actions` it fails.

I guess this is because the build system is skipping files in the parent directory

**Comment by linclark** [comment]
ah, maybe that's why it wasn't working for me

**Comment by bgrins** [comment]
So apparently we are already doing this with mochitest-chrome tests (the utils tests reference the component head.js): https://github.com/devtools-html/gecko-dev/blob/console-frontend/devtools/client/webconsole/new-console-output/test/utils/chrome.ini#L4

**Comment by linclark** [comment]
Clearing out the sprint milestone on this. Moving shared things to modules unblocks the issues that this was blocking, so this is no longer high priority.

**Comment by linclark** [comment]
Since the tests that had separate heads are switching to mocha, we don't need this anymore
