### ISSUE TITLE
Add newline at end of console messages for clipboard compat

### ISSUE THREAD

**Issue by bgrins** [firefox-devtools/original-console-fork#252]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1298225.

Not sure if it's best to inject the newline at the end of each component, or somehow globally when rendering each individual message component: https://github.com/devtools-html/gecko-dev/blob/83b437a4409c96b930245b873d8e29df619f071a/devtools/client/webconsole/new-console-output/components/message-types/console-api-call.js#L110 or in a loop when it renders each message: https://github.com/devtools-html/gecko-dev/blob/83b437a4409c96b930245b873d8e29df619f071a/devtools/client/webconsole/new-console-output/components/console-output.js#L52

**Comment by jsnajdr** [comment]
The legacy console-output has a feature where each message node has a `clipboardText` property, which can be set to any value independent from the HTML markup. The _Copy_ command in the context menu will then copy this value to the clipboard. Instead of the HTML node's `textContent`.

The `clipboardText` feature seems to be broken though and would deserve some cleanup and testing if it wasn't to be replaced soon by the new frontend.

It might be a good idea to implement it this way in the new frontend, instead of fine-tuning the HTML markup.

**Comment by bgrins** [comment]
Since we are already pretty close (and using a lot of the shared components that have just been cleaned up), I'd be OK with adding a new line to the markup for now.

If we end up wanting very different output for messages later on then adding a separate clipboardText seems like a good idea

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307906](https://bugzilla.mozilla.org/show_bug.cgi?id=1307906)
