### ISSUE TITLE
Add rep for long strings

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#277]
Currently, long strings just show up as a blank line.

STR:
1. `Array(10000).fill("a").join("")`

**Comment by nchevobbe** [comment]
There might be a bug in the StringRep, because 

``` javascript
Array(1000).fill("a").join("")
```

does show a truncated string : 

``` javascript
"aaaaaaaaaaaaaaaaaaaaaaaaa…aaaaaaaaaaaaaaaaaaaaaaaa"
```

**Comment by nchevobbe** [comment]
I dug a little and found the issue.

``` javascript
Array(10000).fill("a").join("")
```

does not return directly a string, but a grip with a `longString` type.

Then, in reps.js `getRep` function, we check `grip.class`, which is `undefined` in this case. So it uses the default Rep which is the Object one. And because there's no property, nothing shows up.

If you store the long string in a global, you can access it in the DOM Panel, and you'll see that it describes it as an `Object`, but without property.

Can we fix it here or should we handle this in the Bugzilla workflow ?

**Comment by nchevobbe** [comment]
After talking with Honza about that, I created a bug https://bugzilla.mozilla.org/show_bug.cgi?id=1302982 , and will handle it through the traditional workflow. I think we can close this issue

**Comment by linclark** [comment]
Great, thanks!
