### ISSUE TITLE
Improve performance of showing cached messages

### ISSUE THREAD

**Issue by bgrins** [firefox-devtools/original-console-fork#309]
@linclark here's the WIP patch we went through earlier: https://github.com/bgrins/devtools-patches/blob/master/perf-stuff

**Comment by bgrins** [comment]
This blocks #104

**Comment by bgrins** [comment]
Something else we could do for non cached to improve the bulklog measurement (probably in another commit) would be to buffer up messages before dispatching them and then send them all as an array.

That can be tested on the Lots of Logs button here (caution, on new frontend right now it will jank the browser): http://bgrins.github.io/devtools-demos/console/stress.html

**Comment by linclark** [comment]
We may be able to address both of these cases if we use a [batching reducer](https://twitter.com/dan_abramov/status/656074974533459968). James said they tried that in debugger and it made things [harder to test](http://logs.glob.uno/?c=mozilla%23devtools&s=21+Sep+2016&e=21+Sep+2016&h=debounce#c214682) for them. 

I'm going to give it a try though, because if it works I think it will solve more problems in one go.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1305161](https://bugzilla.mozilla.org/show_bug.cgi?id=1305161)
