### ISSUE TITLE
CSS warnings are missing

### ISSUE THREAD

**Issue by captainbrosset** [firefox-devtools/original-console-fork#320]
This might already be filed somewhere, but I couldn't find it, sorry about that.
CSS warnings seem to be missing in the new console output front-end.

STR:
- open the inspector
- open the split console
- select any element in the inspector
- in the rule-view, enter an invalid declaration like `foo:bar;`

Expected: a warning should be shown: "Unknown property ‘foo’.  Declaration dropped."
Actual: nothing.

Let me add that CSS warnings are a very important learning tool, and I think we should have them sooner rather than later.
Of course you can go in the rule-view and check if there are warning signs next to declarations, but you'd have to select all nodes one by one to see all warnings. In the console, you get all the warnings at once.

I know that gecko hackers also use them.

In fact, we are considering adding even more of these warnings in the future, for "useless" properties for instance, like width:20px; that has no effect on inline elements (see this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1303833)

**Comment by linclark** [comment]
Thanks for filing this.

We weren't sure whether people were using these. Since they aren't available in Chrome's console, we decided to turn them off and see if anyone raised it as an issue.

The only thing that we'll need to figure out before turning this back on is what we want the filter to look like. We currently have the levels and 2 categories, network and XHR. I worry that just adding CSS as another category would potentially make the UI confusing.

@helenvholmes, I was wondering whether you'd have time to revisit the design of the filtering from #101. Nicolas ended up handling network and xhr as buttons instead of a checkbox since we have two kinds of network messages (Chrome only has xhr, IIRC).

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307942](https://bugzilla.mozilla.org/show_bug.cgi?id=1307942)
