### ISSUE TITLE
Allow me to close the side panel of the console

### ISSUE THREAD

**Issue by jnachtigall** [firefox-devtools/original-console-fork#333]
See screenshot. 
![nightly_allow_me_to_close_sidepanel_in_console](https://cloud.githubusercontent.com/assets/3307404/18985417/16b1634a-86f8-11e6-9e66-ffbfefd11238.png)

Once the side panel is open, then there's no way to close it again (except reloading the page or closing the whole devtools). In the inspector there are these "Collapse pane" / "Expand pane" buttons which might be used in the Console as well.

**Comment by nchevobbe** [comment]
As a workaround, you can focus the variable view, and then hit the <kbd>Esc</kbd> key. 
FYI, the variable view is not here to stay, we are planning to switch to some object inspection, although I don't know the detail yet

**Comment by linclark** [comment]
Thanks for posting the issue @jnachtigall. That's a really good point.

@nchevobbe is right, we are planning to remove the variables view in phase 2. Once that is done, you'll be able to inspect an object using a toggler that is output directly next to it. I'm going to close out this issue since it will be resolved when we switch to object inspector in the next phase of work.
