### ISSUE TITLE
Individual line items hard to differentiate

### ISSUE THREAD

**Issue by jnachtigall** [firefox-devtools/original-console-fork#350]
Dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=879310 I would like to raise awareness about. 

I think the line items would be much easier to read if they had alternating background colors like usually done for table rows with CSS `:nth-child(even)` or `:nth-child(odd)`. Especially if you have line items that stretch more than one line (which happens often when the devtools are attached at the right side and not at bottom).

**Comment by nchevobbe** [comment]
I don't really think zebra would be something we want for this, as it would be too "loud". But we can definitely experiments with things that would improve the readibility ( like more vertical padding around the message, separation lines on each message, ... ).
That's a job for @helenvholmes  :ok_woman: :) 

Helen, I'm started to think that maybe we should refresh the look of the console. The icons (and their colors) doesn't feel at odd with the new line-style icons we have in the toolbar, and since we have this as a brand new frontend, it would be nice to be able to launch it and say it got some design love in addition to a complete tech refactor. Let me know what you think about this !

**Comment by jnachtigall** [comment]
Or maybe just a little border-left with different colors, e.g. red for warning. Just an idea.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307929](https://bugzilla.mozilla.org/show_bug.cgi?id=1307929)
