### ISSUE TITLE
Add support for console group

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#44]
We need to figure out:
- How do we prune groups from the head of the list. The current limit is something like 2000 messages. We may increase this, but there will be some upper bound. Does the whole group get pruned? Our current thinking is that messages get pruned individually until all are gone, but that the group header stays in place. It may include a warning that messages have been pruned from the group.
- How are we going to handle nesting?
- How should we model the data?

Tests:
- [ ] browser_webconsole_bug_664131_console_group.js

**Comment by nchevobbe** [comment]
If possible, I'd like to work on it after the filter bar is done, since that's the feature (collapsible group) that leaded me to work on the new console

**Comment by linclark** [comment]
That would be rad! We don't plan to prioritize this for another few sprints, but if you want to take it on when we do I'd love that.

**Comment by nchevobbe** [comment]
FYI I started working on this ( and `console.groupCollapsed`)

**Comment by nchevobbe** [comment]
I got the basic working, now I must see how to deal with filtering and pruning.

@helenvholmes , I'm not happy with what I have for collapsible group for now : 

![screenshot at sept 29 21-49-16](https://cloud.githubusercontent.com/assets/578107/18969914/7c66b8ca-868f-11e6-9b2b-188c2f8396c9.png)

I think this could be much better. Do you think you could have design something quickly, especially regarding borders and alignment ?  Thanks !

**Comment by linclark** [comment]
@nchevobbe even in their current raw design state, it is sooooo cool to see real live console.groups! So excited!

**Comment by helenvholmes** [comment]
I agree, these look great!

Since you asked for designs I threw something together, although all of my suggestions are very minimal:
1. I would round off the edges of the group lines, and bump them down from 2px to 1.
2. I would use the `var(--theme-splitter-color)` for their background color. (They're guiding lines, so I think it's okay if they're faint.)
3. I would left-align line up the clear button in the toolbar to the command-pick; this technically isn't in scope for your patch, but it will help the groups and console logs look more lined up generally.
4. I would use `var(--theme-splitter-color)` for the warning circles, too, with a hover color if they have additional information (I don't know if they do). Suggestion: `#ced2d6`
5. I think you can tighten the spacing between "log" and those warning circles; they look disconnected currently.

![screen shot 2016-10-04 at 11 15 18 am](https://cloud.githubusercontent.com/assets/1720093/19080067/e03860fa-8a23-11e6-8c8c-f83cde20fccf.png)

**Comment by nchevobbe** [comment]
Thanks for thinking about this @helenvholmes , i'll try to have those in my PR.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307873](https://bugzilla.mozilla.org/show_bug.cgi?id=1307873)
