### ISSUE TITLE
PageError component should output element that looks like error

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#55]
In the current console, this is done in a CSS rule on the `severity` attribute ( https://dxr.mozilla.org/mozilla-central/source/devtools/client/themes/webconsole.css#190 ).
AFAIK we can't have such an attribute in the output dom with React, so I guess we have add a CSS rule on another attribute ( `data-severity` if possible ? ).
@linclark , @bgrins , is my understanding of this correct ?

**Comment by linclark** [comment]
@nchevobbe you're right, React only allows custom attributes if they are `data-*` attributes... except for this one weird trick you can do. If you put an "is" property in the props object, it will interpret it as a Web Component and allow all sorts of attributes. One thing to watch out for—if you do this, then you have to use "class" instead of "className".

You can see an example of this in a [PR that hasn't landed](https://github.com/bgrins/gecko-dev/pull/25/files#diff-f4969db5deaefddeb828c7b2a0832511R34) yet.

We could use this hack, and I would lean towards that to make things simpler for now. Then again, we will need to change this eventually, so if you have an idea for how you want to handle it, please feel free to try that out.

**Comment by nchevobbe** [comment]
Okay, so if we go that way in the consoleApi component I'd prefer do the same on the pageError component for consistency sake (and we won't have to modify the CSS files for each theme ), at least for now .
Thanks for the tip, I'll have a look tonight

**Comment by nchevobbe** [comment]
Fixed by https://github.com/bgrins/gecko-dev/pull/64
