### ISSUE TITLE
Make sure all existing tests pass

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#59]
All of the existing tests in the webconsole should continue to pass.

Depends on #58

**Comment by nchevobbe** [comment]
I don't know if it is what you meant, but I launched `./mach test /Users/nicolaschevobbe/Projects/gecko-dev/devtools/client/webconsole/test/` and 2 tests fail : 

`TEST-UNEXPECTED-FAIL | devtools/client/webconsole/test/browser_repeated_messages_accuracy.js | Exception thrown - at chrome://mochitests/content/browser/devtools/client/webconsole/test/browser_repeated_messages_accuracy.js:96 - SyntaxError: expected expression, got '}'`

This is due to a syntax error in the file, caused by https://github.com/bgrins/gecko-dev/commit/86d732f8bdc28f1be1d3402a6f12c6807a78c27b#diff-25b665c4b41699507218583014981843R98

The second one is :
`3 INFO TEST-UNEXPECTED-FAIL | devtools/client/webconsole/test/browser_bug_865288_repeat_different_objects.js | Exception thrown - This test didn't call add_task, nor did it define a generatorTest() function, nor did it define a test() function, so we don't know how to run it.`
Which is due to https://github.com/bgrins/gecko-dev/commit/86d732f8bdc28f1be1d3402a6f12c6807a78c27b#diff-8f91bb7e13b930e8b709263d25277aaaR1

Should those 2 tests reverted to what they used to be before https://github.com/bgrins/gecko-dev/pull/26 ?

**Comment by linclark** [comment]
Thanks for testing this. I'm planning to format the patches in a way that will skip any changes to test, so it should be fine.

I've rebased and pushed it up to try (with the test directory changes reverted). Let's see how it does!

https://treeherder.mozilla.org/#/jobs?repo=try&revision=c6990306f133

**Comment by linclark** [comment]
@bgrins It seems that `client/webconsole/net/main.js` and `client/webconsole/new-console-output/main.js` define `rootUrl` and (more importantly) `require` in the same scope in conflicting ways. Any ideas on how to address this?

**Comment by bgrins** [comment]
Oh, hm yeah that's a problem.  A couple of ideas:
- Maybe we could we load up the new-console-output module in an iframe so the global could be attached there (of course the element would still be rendered into the parent frame(
- We could define it as newConsoleOutput.require() and change all modules to use that (basically store the BrowserLoader instance into a variable).

Or, maybe we don't actually need to dump `require` on the global, and the BrowserLoader and instead expose this.require as a global in the BrowserLoader so any module loaded by it will automatically have it available (in this case starting with the `OutputWrapperThingy`).  I can check and see if that would work.

**Comment by jryans** [comment]
Modules **loaded by** `BrowserLoader` should already have `require` as a global. Let me know if you're seeing something different in this case.

**Comment by bgrins** [comment]
Turns out we are assigning 'require' to the window for no reason as per https://github.com/bgrins/gecko-dev/issues/59#issuecomment-215167723.  I'll send a PR with a fix

**Comment by linclark** [comment]
new try push: https://treeherder.mozilla.org/#/jobs?repo=try&revision=fe8c6439390b

**Comment by linclark** [comment]
ok, this is the series that I think we're going to land: https://treeherder.mozilla.org/#/jobs?repo=try&revision=adf43c335821&selectedJob=20170548
