### ISSUE TITLE
Make the console take the full width of the window

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#71]
In the old console, it is done in the `resize` function (https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#621).
I don't know if we should only do the same thing for `this.experimentalOutputNode`, if it exists, in the same function, or if it should be handled at a higher level (see https://github.com/bgrins/gecko-dev/blob/console-frontend/devtools/client/webconsole/webconsole.js#L574).

**Comment by linclark** [comment]
Good thinking. @bgrins would probably have an opinion on this since he did the original fix.

**Comment by bgrins** [comment]
We had to land that because of some really serious perf issues with the flexed container: https://bugzilla.mozilla.org/show_bug.cgi?id=1237368#c5.  It may not be necessary with the new frontend but I'm not sure.

One approach would be to re-land something similar to https://hg.mozilla.org/integration/fx-team/rev/1aed451f1502#l1.11 but with CSS flex when it's the new frontend, then conditionally don't do anything on 'resize' function.

My feeling right now though is to stick with the current resize() function and handle that later on when we can measure perf on a more stable target.  It might just need to be that we call resize() more frequently although hopefully all calls can be limited to when messages are dispatched in webconsole.js and outside of the new frontend (not sure how possible that will be though - it might be that we need to call up to the webconsole's resize when the render happens for the top level component).

**Comment by bgrins** [comment]
Fixed by #80
